#image

FROM node:18.16-alpine AS builder

# working directory

WORKDIR /app

# copy package.json and install dependencies

COPY package.json package-lock.json ./
RUN npm install

# copy rest

COPY . .

# build react app

RUN npm run build

# serve with Nginx

FROM nginx:alpine

# copy production build output from builder stage

COPY --from=builder /app/build /usr/share/nginx/html

# expose port 80 for HTTP

EXPOSE 80

# run Nginx to server React app

CMD ["nginx", "-g", "daemon off;"]