version: '3.8'

services:
  # React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - vibestream-net

  # Express Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - '3001'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_CALLBACK_URL=${SPOTIFY_CALLBACK_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_CALLBACK=${SENDGRID_CALLBACK}
      - CLIENT_URL=${CLIENT_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - REACT_APP_CLIENT_URL=${REACT_APP_CLIENT_URL}
      - SPOTIFY_BASE_URL=${SPOTIFY_BASE_URL}
    depends_on:
      - mongo
    networks:
      - vibestream-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  vibestream-net:
    driver: bridge
