version: '3'

services:
  server:
    build: ./server
    ports:
      - '3001:3001'
    env_file:
      - ./server/.env
  client:
    build: ./client
    ports:
      - '3000:80'
    environment:
      - SERVER_NAME=_
      - BACKEND_HOST=server
      - BACKEND_PORT=3001
    depends_on:
      - server
