version: '3.8'

services:
  # React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - vibestream-net

  # Express Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - '3001'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGO_URI}
    depends_on:
      - mongo
    networks:
      - vibestream-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    volumes:
      - mongo-db-data:/data/db
    networks:
      - vibestream-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    expose:
      - '27017'

volumes:
  mongo-db-data:

networks:
  vibestream-net:
    driver: bridge
